### ISSUE TITLE
For Cud?

### ISSUE THREAD

**Issue by Alexey-T** [mpatrick/Sublime-Dark-Matter-Theme#2]
Hi Patrick;
Maybe possible to adapt theme for CudaText?
It has visual dialog to edit theme (Options/ Settings-more/ colors)

**Comment by patrickemuller** [comment]
Hey @Alexey-T I'm not using this Theme right now because I migrated from Sublime to ATOM. Never used CudaText before, don't know how to create a theme for it 😢

**Comment by Alexey-T** [comment]
well, dialog  (Options/ Settings-more/ Sett-colors) is theme configurer. it is colors for ui, and styles for lexers/syntax.
